# Generated by Django 3.1.5 on 2021-01-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
