# Generated by Django 3.1.5 on 2021-01-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20210113_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.TextField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
