# Generated by Django 3.1.5 on 2021-01-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20210113_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('list_points', models.TextField(blank=True)),
                ('max_people', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
