# Generated by Django 3.1.5 on 2021-01-14 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_gallery_galleryimage_restaurantdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestaurantDetails',
            new_name='RestaurantDetail',
        ),
    ]
