# Generated by Django 3.1.5 on 2021-01-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20210114_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdetail',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
