# Generated by Django 3.1.5 on 2021-01-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20210114_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='images',
            field=models.ImageField(upload_to='gallery/'),
        ),
    ]
