# Generated by Django 3.1.5 on 2021-01-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_auto_20210114_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdetail',
            name='mail',
            field=models.EmailField(default='info@vivacerestaurant.co.nz', max_length=254),
            preserve_default=False,
        ),
    ]
