# Generated by Django 3.1.5 on 2021-01-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='image',
            field=models.ImageField(default='', upload_to='function/'),
            preserve_default=False,
        ),
    ]
