# Generated by Django 3.1.5 on 2021-01-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_auto_20210118_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinginfo',
            old_name='date',
            new_name='booking_date',
        ),
    ]
