# Generated by Django 3.1.5 on 2021-01-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_auto_20210118_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdetail',
            name='is_reservantion_open',
            field=models.BooleanField(default=True),
        ),
    ]
