# Generated by Django 3.1.5 on 2021-01-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_restaurantdetail_is_reservantion_open'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantdetail',
            old_name='is_reservantion_open',
            new_name='is_reservation_open',
        ),
    ]
