# Generated by Django 3.1.5 on 2021-01-19 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_drinkscategory_drinksmenu_drinkssubcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Enquiry',
        ),
        migrations.AlterModelOptions(
            name='award',
            options={'verbose_name_plural': 'Awards Obtained'},
        ),
        migrations.AlterModelOptions(
            name='bookinginfo',
            options={'verbose_name_plural': 'Booking Information'},
        ),
        migrations.AlterModelOptions(
            name='detail',
            options={'verbose_name_plural': 'About Us Information'},
        ),
        migrations.AlterModelOptions(
            name='drinkscategory',
            options={'verbose_name_plural': 'Drinks Category'},
        ),
        migrations.AlterModelOptions(
            name='drinksmenu',
            options={'verbose_name_plural': 'Drinks Menu'},
        ),
        migrations.AlterModelOptions(
            name='drinkssubcategory',
            options={'verbose_name_plural': 'Drinks Sub Category'},
        ),
        migrations.AlterModelOptions(
            name='enquiry',
            options={'verbose_name_plural': 'Customer Enquiry'},
        ),
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name_plural': 'Food Category'},
        ),
        migrations.AlterModelOptions(
            name='foodmenu',
            options={'verbose_name_plural': 'Food Menu'},
        ),
        migrations.AlterModelOptions(
            name='function',
            options={'verbose_name_plural': 'Event Information'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery Categories'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name_plural': 'Images to Upload to Gallery'},
        ),
        migrations.AlterModelOptions(
            name='restaurantdetail',
            options={'verbose_name_plural': 'Restaurant Information'},
        ),
    ]
