# Generated by Django 3.1.5 on 2021-01-19 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_auto_20210119_1426'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail',
            new_name='AboutUs',
        ),
    ]
