# Generated by Django 3.1.5 on 2021-01-31 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_auto_20210119_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdetail',
            name='fb_page',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='restaurantdetail',
            name='insta_page',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
